from __future__ import annotations

from rich.console import Group
from rich.text import Text

from elva_cli.core.services.import_result import DryRunResult, ImportSpecResult  # noqa: TC001
from elva_cli.ui.renderables.base import aligned_rows, render


def _spec_rows(result: ImportSpecResult | DryRunResult) -> list[tuple[str, Text, Text]]:
    rows = [("format", Text(result.spec_format), Text(""))]
    if result.spec_title is not None:
        rows.append(("title", Text(result.spec_title), Text("")))
    if result.spec_version is not None:
        rows.append(("version", Text(result.spec_version), Text("")))
    if result.endpoints is not None:
        rows.append(("endpoints", Text(str(result.endpoints)), Text("")))
    return rows


@render.register
def _(result: ImportSpecResult) -> Group:
    headline = Text(
        f"{result.action.capitalize()} {result.collection!r} from {result.source}.",
        style="elva.ok",
    )

    rows = [("workspace", Text(result.workspace), Text("")), *_spec_rows(result)]
    rows.append(("collection id", Text(result.collection_id, style="elva.dim"), Text("")))
    if result.url is not None:
        rows.append(("url", Text(result.url, style="elva.accent"), Text("")))

    body = [headline, Text(""), aligned_rows(rows)]

    if not result.metadata_confirmed:
        body += [
            Text(""),
            Text(
                "The upload succeeded, but Elva had not finished reading the spec "
                "in time — the details above may still describe the previous one.",
                style="elva.warn",
            ),
        ]
    elif result.endpoints == 0:
        body += [
            Text(""),
            Text(
                "No endpoints were found. The file uploaded, but Elva could not "
                "read any operations out of it — check the spec is valid.",
                style="elva.warn",
            ),
        ]

    if result.published_mcps:
        body += [Text(""), _mcp_warning(result.published_mcps)]

    return Group(*body)


def _mcp_warning(mcps: tuple[str, ...]) -> Text:
    """MCP tools are generated when a server is published and are not
    regenerated by a spec update, so the old ones stay live and answering."""
    listed = ", ".join(mcps)
    one = len(mcps) == 1
    return Text(
        f"This collection has {'a' if one else len(mcps)} published MCP "
        f"{'server' if one else 'servers'} ({listed}). "
        f"{'Its' if one else 'Their'} tools were generated from the spec "
        f"{'it was' if one else 'they were'} published with and are not regenerated "
        f"by this update — republish {'it' if one else 'them'} to pick up the change.",
        style="elva.warn",
    )


@render.register
def _(result: DryRunResult) -> Group:
    headline = Text(
        f"Would {result.action} {result.collection!r} from {result.source}.",
        style="elva.accent",
    )

    rows = _spec_rows(result)
    if result.size_bytes is not None:
        rows.append(("size", Text(f"{result.size_bytes / 1024:.1f} KB"), Text("")))

    return Group(
        headline,
        Text(""),
        aligned_rows(rows),
        Text(""),
        Text("Nothing was sent. Drop --dry-run to do it.", style="elva.dim"),
    )
